module.exports = [
  {
    slug: 'shoe-rock-vision-srv-sneakers-blue',
    name: 'Shoe Rock Vision(SRV) Sneakers (Blue)',
    is_new: true,
    images: ['/img/d1.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/d2.jpg',
    price: 300,
    sale_price: 200,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'chikku-loafers',
    name: 'Chikku Loafers',
    is_new: false,
    images: ['/img/s8.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/s8.jpg',
    price: 650,
    sale_price: 550,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'shuberry-heels',
    name: 'Shuberry heels',
    is_new: false,
    images: ['/img/s4.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/s4.jpg',
    price: 200,
    sale_price: null,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'running-shoes',
    name: 'Running Shoes',
    is_new: false,
    images: ['/img/s7.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/s7.jpg',
    price: 300,
    sale_price: 200,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'shoe-rock-vision-srv-sneakers-blue-new',
    name: 'Shoe Rock Vision(SRV) Sneakers (Blue)',
    is_new: true,
    images: ['/img/d1.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/d2.jpg',
    price: 300,
    sale_price: 200,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'chikku-loafers-new',
    name: 'Chikku Loafers',
    is_new: false,
    images: ['/img/s8.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/s8.jpg',
    price: 650,
    sale_price: 550,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'shuberry-heels-new',
    name: 'Shuberry heels',
    is_new: false,
    images: ['/img/s4.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/s4.jpg',
    price: 200,
    sale_price: null,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
  {
    slug: 'running-shoes-new',
    name: 'Running Shoes',
    is_new: false,
    images: ['/img/s7.jpg', '/img/d2.jpg', '/img/d3.jpg'],
    cover: '/img/s7.jpg',
    price: 300,
    sale_price: 200,
    rate: 4.5,
    short_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor.',
    description: '<div class="single_page"><h6>Lorem ipsum dolor sit amet</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p><p class="para">Lorem ipsum dolor sit amet, consectetur adipisicing elPellentesque vehicula augue eget nisl ullamcorper, molestie blandit ipsum auctor. Mauris volutpat augue dolor.Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco. labore et dolore magna aliqua.</p></div>',
  },
];